baseURL = "localhost" #"https://kmsaumcis.github.io/mcis6273_f17_datamining"
languageCode = "en-us"
title = "MCIS6273 | Data Mining | Fall 2018"
theme = "hugo-xkmin"
pygmentsUseClasses = true
pygmentCodeFences = true


[Params]
  dateFormat = "January 2, 2006"
  commit = false
  rss = true

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "Syllabus"
    url = "syllabus/"
    weight = 2
[[menu.main]]
    name = "Homework"
    url = "homework/"
    weight = 3
#[[menu.main]]
#    name = "Lecture Notes"
#    url = "notes/"
#    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "index.xml"

